services:
  mongodb:
    image: mongo:7
    container_name: emotion_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: emotion_backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DB_NAME: emotion_platform
      JWT_SECRET: change_me
      CORS_ORIGINS: '["http://localhost:5173"]'
      MODEL_ARTIFACT_PATH: /artifacts/text_emotion_model.joblib
    volumes:
      - ../ml/artifacts:/artifacts:ro
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  ml:
    build:
      context: ../ml
      dockerfile: Dockerfile
    container_name: emotion_ml
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ../ml/artifacts:/app/artifacts

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: emotion_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    profiles:
      - frontend

volumes:
  mongo_data:
